# -*- coding: utf-8 -*-
"""EEX6278_419218352_AMTS_Adikary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/187ULB7TWHFNiY_S0nZ2_XZ9NQdejmh_s
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""Importing as a CSV File"""

df=pd.read_csv("/content/penguins.csv")
print(df)

"""Cleaning Data by removing null values"""

df.dropna(inplace=True)
print(df)

from sklearn.preprocessing import LabelEncoder
x=df.iloc[:,2:6].values
y=df.iloc[:,0].values
print(x)
print(y)

encorder=LabelEncoder()
y1=encorder.fit_transform(y)
print(y1)

y=pd.get_dummies(y1).values
print(y)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

import numpy as np
from tensorflow import keras

# Define the architecture of the neural network
model = keras.Sequential([
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])

x = np.asarray(x).astype(np.float32)

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=30, epochs=10)

loss, accuracy = model.evaluate(x_test, y_test)
print("Test loss:", loss)
print("Test accuracy:", accuracy)